/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gohar.Munir (https://sketchfab.com/Gohar.Munir)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-computer-chair-6148d2bbb5b041209dd3f021f476c320
title: Low Poly Computer Chair
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/models/chair/scene.gltf");
  return (
    <group ref={group} {...props} dispose={null} position={[-100,0,-100]} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Computer_Chair_High_Heels_2_0.geometry}
            material={materials.High_Heels_2}
            scale={[15, 15, 15]}
            rotation={[0, -Math.PI / 2, 0]}
            position={[120,0,20]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/chair/scene.gltf");
