/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: felixawani (https://sketchfab.com/felixawani)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/05353724b7884bfb81211c7033a57fd4
title: Computer Desk
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Cube_0.geometry} material={nodes.Cube_0.material} />
        <group position={[-2.35, 0, -1.49]}>
          <mesh geometry={nodes.Cube002_0.geometry} material={nodes.Cube002_0.material} />
        </group>
        <group position={[0, 0.8, -1.05]}>
          <mesh geometry={nodes.Cube003_0.geometry} material={nodes.Cube003_0.material} />
        </group>
        <group position={[-1.52, -1.25, -0.2]}>
          <mesh geometry={nodes.Cube004_0.geometry} material={nodes.Cube004_0.material} />
        </group>
        <group position={[2.35, 0, -1.49]}>
          <mesh geometry={nodes.Cube001_0.geometry} material={nodes.Cube001_0.material} />
        </group>
        <group position={[1.52, -1.25, -0.2]}>
          <mesh geometry={nodes.Cube005_0.geometry} material={nodes.Cube005_0.material} />
        </group>
        <group position={[0, -1.25, -0.2]}>
          <mesh geometry={nodes.Cube006_0.geometry} material={nodes.Cube006_0.material} />
        </group>
        <group position={[-1.52, -0.29, -0.3]}>
          <mesh geometry={nodes.Cube007_0.geometry} material={nodes.Cube007_0.material} />
        </group>
        <group position={[0, -0.29, -0.3]}>
          <mesh geometry={nodes.Cube008_0.geometry} material={nodes.Cube008_0.material} />
        </group>
        <group position={[1.52, -0.29, -0.3]}>
          <mesh geometry={nodes.Cube009_0.geometry} material={nodes.Cube009_0.material} />
        </group>
        <group position={[-0.76, -0.21, -0.2]}>
          <mesh geometry={nodes.Cube010_0.geometry} material={nodes.Cube010_0.material} />
        </group>
        <group position={[0.76, -0.21, -0.2]}>
          <mesh geometry={nodes.Cube011_0.geometry} material={nodes.Cube011_0.material} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
