/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Eric Fan (https://sketchfab.com/ericfan1992)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/fc1b43e332d147edb7dca8f89cffa4d7
title: Book
*/

import React, { useRef } from "react";
import { useGLTF, Text } from "@react-three/drei";
import { useRouter } from "next/router";
import Link from "next/link";
export default function Model({ ...props }) {
  const group = useRef();
  const router = useRouter();
  const { nodes, materials } = useGLTF("/models/book/scene.gltf");
  return (
    <>
      <group
        ref={group}
        {...props}
        dispose={null}
        scale={[40, 40, 40]}
        position={[10, 37, 0]}
        onClick={() => {
          window.open(`${window.location.href}projects`);
        }}
      >
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Architexture_0.geometry}
            material={materials.Architexture}
          />
          <mesh
            geometry={nodes.Architexture_1.geometry}
            material={materials.Bookpage}
          />
        </group>
      </group>
      <Text
        color={"#000000"}
        fontSize={5}
        lineHeight={1}
        letterSpacing={0.02}
        textAlign={"left"}
        anchorX="center"
        anchorY="middle"
        position={[26, 37.2, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        {"Projects"}
      </Text>
    </>
  );
}

useGLTF.preload("/models/book/scene.gltf");
